# Generated by Django 4.2.7 on 2023-12-01 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_elegirrespuesta_pregunta_quizusuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitivo', models.CharField(max_length=50)),
                ('past', models.CharField(max_length=50)),
                ('participe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'verbo',
            },
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='Pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='myapp.pregunta'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='quizUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='myapp.quizusuario'),
        ),
    ]
