# Generated by Django 4.2.7 on 2023-12-02 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_padre1_alter_verbo_infinitivo_delete_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padre_verbos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='verbo',
            name='infinitivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.padre_verbos'),
        ),
        migrations.DeleteModel(
            name='Padre1',
        ),
    ]
