# Generated by Django 4.2.7 on 2023-12-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_padre_verbos_alter_verbo_infinitivo_delete_padre1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Padre_verbos',
            new_name='Origen',
        ),
        migrations.RenameField(
            model_name='origen',
            old_name='principal',
            new_name='original',
        ),
    ]
