# Generated by Django 4.2.7 on 2023-12-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_padre_verbos_origen_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verbo',
            table=None,
        ),
    ]
