# Generated by Django 4.2.7 on 2023-12-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_verbo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verbo',
            name='infinitivo',
            field=models.CharField(max_length=50),
        ),
    ]
