# Generated by Django 4.2.7 on 2023-12-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_verbo_infinitivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verbosregulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitivo', models.CharField(max_length=50)),
                ('past', models.CharField(max_length=50)),
                ('participe', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'verbo_regulares',
            },
        ),
    ]
