# Generated by Django 4.2.7 on 2023-12-04 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_verbosregulares'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verbosregulares',
            table='verbo_irregulares',
        ),
    ]
