# Generated by Django 4.2.7 on 2023-12-04 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_verbosregulares_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verbosregulares',
            new_name='Verbosirregulares',
        ),
    ]
