# Generated by Django 4.2.7 on 2023-12-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_verbosregulares_verbosirregulares'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Verbosirregulares',
            new_name='Irregular',
        ),
        migrations.AlterModelTable(
            name='irregular',
            table='irregular',
        ),
    ]
