# Generated by Django 4.2.7 on 2023-12-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_adjetivo_remove_task_user_remove_tomoagua_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjetivo',
            old_name='advetivo',
            new_name='adjetivo',
        ),
    ]
