# Generated by Django 4.2.7 on 2023-12-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_advetivo_adjetivo_adjetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerundio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbo', models.CharField(max_length=50)),
                ('gerundio', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'gerundio',
            },
        ),
    ]
