# Generated by Django 4.2.7 on 2023-12-05 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_gerundio'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba1', models.CharField(max_length=50)),
                ('prueba2', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='prueba2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prueba2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prueba', to='myapp.prueba1')),
            ],
        ),
    ]
