# Generated by Django 4.2.7 on 2023-12-05 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_prueba1_prueba2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past', models.CharField(max_length=50)),
                ('participe', models.CharField(max_length=50)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pruebas', to='myapp.elegirrespuesta')),
            ],
            options={
                'db_table': 'prueba',
            },
        ),
        migrations.RemoveField(
            model_name='prueba2',
            name='prueba2',
        ),
        migrations.DeleteModel(
            name='prueba1',
        ),
        migrations.DeleteModel(
            name='prueba2',
        ),
    ]
