# Generated by Django 4.2.7 on 2023-12-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_prueba_remove_prueba2_prueba2_delete_prueba1_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prueba',
            table=None,
        ),
    ]
