# Generated by Django 4.2.7 on 2023-12-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_prueba_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prueba',
            table='prueba',
        ),
    ]
