# Generated by Django 4.2.7 on 2023-12-05 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_prueba_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
