# Generated by Django 4.2.7 on 2023-12-05 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba_regulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past', models.CharField(max_length=50)),
                ('participe', models.CharField(max_length=50)),
                ('gerundio', models.CharField(max_length=50)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pruebas', to='myapp.elegirrespuesta')),
            ],
            options={
                'db_table': 'prueba',
            },
        ),
    ]
