# Generated by Django 4.2.7 on 2023-12-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_prueba_regulares'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba_regular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('past', models.CharField(max_length=50)),
                ('participe', models.CharField(max_length=50)),
                ('gerundio', models.CharField(max_length=50)),
                ('texto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pruebas_regulares', to='myapp.elegirrespuesta')),
            ],
            options={
                'db_table': 'prueba_regular',
            },
        ),
        migrations.DeleteModel(
            name='Prueba_regulares',
        ),
    ]
