# Generated by Django 4.2.7 on 2023-12-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_prueba_regular_delete_prueba_regulares'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba_regular',
        ),
    ]
