# Generated by Django 4.2.7 on 2023-12-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_prueba_regular'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Origen',
        ),
    ]
