# Generated by Django 4.2.7 on 2023-12-10 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_delete_origen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gerundio',
        ),
        migrations.DeleteModel(
            name='Verbo',
        ),
        migrations.RenameField(
            model_name='irregular',
            old_name='infinitivo',
            new_name='gerundio',
        ),
    ]
