# Generated by Django 4.2.7 on 2023-12-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_delete_gerundio_delete_verbo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Irregular',
        ),
    ]
